workflows:
  android-release:
    name: SmartPOS Pro APK Build
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Go to project root
        script: cd $CM_BUILD_DIR
      - name: Create android folder if missing
        script: flutter create .
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
